import type { AsyncTranslationAdapter, TranslationAdapter } from "@form-engine-ts/core";

export type TranslationCatalog = Readonly<Record<string, string>>;
export type TranslationCatalogs = Readonly<Record<string, TranslationCatalog>>;

const sharedEnglish: TranslationCatalog = {
  "form.title": "Customer feedback",
  "form.description": "Tell us about your experience. Required fields are marked.",
  "form.submit": "Send response",
  "form.back": "Back",
  "form.next": "Next",
  "form.step": "Step {{current}} of {{total}}",
  "form.draftRestored": "Draft restored",
  "field.name.label": "Your name",
  "field.name.help": "Enter at least {{min}} characters.",
  "field.name.placeholder": "Ada Lovelace",
  "field.reference.label": "Reference code",
  "field.reference.help": "Use three uppercase letters followed by three digits.",
  "field.reference.placeholder": "ABC123",
  "field.comments.label": "What could we improve?",
  "field.comments.placeholder": "Share the details that matter most…",
  "field.age.label": "Your age",
  "field.age.placeholder": "18–100",
  "field.team.label": "Team",
  "field.team.help": "Choose the team you worked with.",
  "field.channels.label": "How did you contact us?",
  "field.channels.help": "Choose one or two channels.",
  "field.consent.label": "I agree that this response may be analyzed.",
  "field.recommend.label": "Would you recommend us?",
  "field.rating.label": "How would you rate your experience?",
  "field.followup.label": "What made the experience disappointing?",
  "option.team.product": "Product",
  "option.team.support": "Support",
  "option.team.sales": "Sales",
  "option.channel.email": "Email",
  "option.channel.chat": "Chat",
  "option.channel.phone": "Phone",
  "option.yes": "Yes",
  "option.no": "No",
  "validation.required": "This field is required.",
  "validation.invalidType": "Enter a value in the expected format.",
  "validation.minLength": "Enter at least {{min}} characters.",
  "validation.maxLength": "Enter no more than {{max}} characters.",
  "validation.pattern": "Use the requested format.",
  "validation.min": "Enter a value of at least {{min}}.",
  "validation.max": "Enter a value no greater than {{max}}.",
  "validation.step": "Use increments of {{step}}.",
  "validation.invalidOption": "Choose one of the available options.",
  "validation.minSelections": "Choose at least {{min}} options.",
  "validation.maxSelections": "Choose no more than {{max}} options.",
  "validation.unknownField": "This response contains an unknown field.",
  "preview.language": "Language",
  "preview.success": "Response saved. Thank you!",
  "preview.error": "The response could not be saved. Try again.",
  "preview.analytics": "Analytics dashboard",
  "preview.responses": "Responses",
  "preview.noResponses": "Submit the form to see aggregate results.",
  "preview.answered": "Answered",
  "preview.unanswered": "Unanswered",
  "preview.minimum": "Minimum",
  "preview.maximum": "Maximum",
  "preview.average": "Average",
  "preview.total": "Total",
  "preview.true": "Checked",
  "preview.false": "Not checked",
  "preview.builder": "Form Builder",
  "preview.mui": "MUI Mode",
  "preview.comparison": "Translation Comparison",
  "preview.respondent": "Respondent Preview",
  "preview.export": "Download CSV",
  "preview.schemaJson": "Schema JSON",
  "preview.storage": "Storage",
  "preview.memory": "Memory",
  "preview.localStorage": "LocalStorage",
  "preview.freeText": "Free-text responses",
  "preview.resetResponses": "Reset responses",
  "preview.resetConfirmation": "Delete every response for this form?",
  "preview.confirmReset": "Confirm reset",
  "preview.cancel": "Cancel",
  "preview.resetSuccess": "All responses for this form were deleted.",
  "preview.resetError": "Responses could not be deleted.",
  "preview.resetUnavailable": "The selected storage does not support response reset.",
  "preview.crossTab": "Cross tabulation",
  "preview.rowQuestion": "Row question",
  "preview.colQuestion": "Column question",
  "preview.webhook": "Webhook simulation",
  "preview.webhookUrl": "Webhook URL",
  "preview.simulateWebhook": "Send simulated event",
  "preview.webhookSuccess": "The simulated webhook was accepted.",
  "preview.webhookError": "The simulated webhook failed.",
  "builder.formBuilder": "Form builder",
  "builder.moveUp": "Move {{title}} up",
  "builder.moveDown": "Move {{title}} down",
  "builder.delete": "Delete {{title}}",
  "builder.deleteAction": "Delete",
  "builder.questionTitle": "質問文 / Question Title",
  "builder.questionTitlePlaceholder": "Example: Tell us what we could improve",
  "builder.completionMessage": "Completion message",
  "builder.newQuestionTitle": "New question",
  "builder.type": "Type",
  "builder.required": "Required",
  "builder.minimum": "Minimum",
  "builder.maximum": "Maximum",
  "builder.options": "Options",
  "builder.optionLabel": "選択肢 / Option Label {{index}}",
  "builder.optionLabelPlaceholder": "Example: Very satisfied",
  "builder.newOptionLabel": "Option {{index}}",
  "builder.remove": "Remove",
  "builder.addOption": "Add option",
  "builder.displayCondition": "Display condition",
  "builder.alwaysVisible": "Always visible",
  "builder.conditionOperator": "Condition operator",
  "builder.conditionValue": "Condition value",
  "builder.conditionTrue": "true",
  "builder.conditionFalse": "false",
  "builder.addQuestion": "Add question",
  "builder.pages": "Page manager",
  "builder.enablePages": "Enable multi-step pages",
  "builder.addPage": "Add page",
  "builder.newPage": "New page",
  "builder.pageTitle": "Page title",
  "builder.pageDescription": "Page description",
  "builder.pageQuestion": "Question to move to the new page",
  "builder.questionPage": "Page",
  "builder.pageCondition": "Page display condition",
  "builder.localization": "Localization",
  "builder.defaultLocale": "Default locale",
  "builder.supportedLocales": "Supported locales",
  "builder.addLocale": "Add locale",
  "builder.editLocale": "Edit locale",
  "builder.autoTranslate": "Translate all text",
  "builder.translationUnavailable": "Provide an async translation adapter to enable automatic translation.",
  "builder.actions.addField": "Add question",
  "builder.fields.selectType": "Select field type",
  "builder.fields.typeText": "Text",
  "builder.fields.typeTextarea": "Textarea",
  "builder.fields.typeNumber": "Number",
  "builder.fields.typeRating": "Rating",
  "builder.fields.typeSelect": "Select",
  "builder.fields.typeMultiSelect": "Multi-select",
  "builder.fields.typeCheckbox": "Checkbox",
  "builder.fields.typeRadio": "Radio",
  "builder.fieldType.text": "Text",
  "builder.fieldType.textarea": "Textarea",
  "builder.fieldType.number": "Number",
  "builder.fieldType.rating": "Rating",
  "builder.fieldType.select": "Select",
  "builder.fieldType.multi-select": "Multi-select",
  "builder.fieldType.checkbox": "Checkbox",
  "builder.fieldType.radio": "Radio",
  "builder.operator.equals": "equals",
  "builder.operator.not_equals": "does not equal",
  "builder.operator.contains": "contains",
  "builder.operator.not_empty": "is not empty"
};

const sharedJapanese: TranslationCatalog = {
  "form.title": "お客様アンケート",
  "form.description": "ご利用体験についてお聞かせください。必須項目には印があります。",
  "form.submit": "回答を送信",
  "form.back": "戻る",
  "form.next": "次へ",
  "form.step": "ステップ {{current}} / {{total}}",
  "form.draftRestored": "下書きを復元しました",
  "field.name.label": "お名前",
  "field.name.help": "{{min}}文字以上で入力してください。",
  "field.name.placeholder": "山田 太郎",
  "field.reference.label": "参照コード",
  "field.reference.help": "英大文字3文字と数字3桁で入力してください。",
  "field.reference.placeholder": "ABC123",
  "field.comments.label": "改善してほしい点",
  "field.comments.placeholder": "特に重要な点をご記入ください…",
  "field.age.label": "年齢",
  "field.age.placeholder": "18〜100",
  "field.team.label": "担当チーム",
  "field.team.help": "ご利用になったチームを選択してください。",
  "field.channels.label": "お問い合わせ方法",
  "field.channels.help": "1つまたは2つ選択してください。",
  "field.consent.label": "この回答を分析に利用することに同意します。",
  "field.recommend.label": "他の方におすすめしますか？",
  "field.rating.label": "今回の体験を評価してください",
  "field.followup.label": "残念だった理由を教えてください",
  "option.team.product": "製品",
  "option.team.support": "サポート",
  "option.team.sales": "営業",
  "option.channel.email": "メール",
  "option.channel.chat": "チャット",
  "option.channel.phone": "電話",
  "option.yes": "はい",
  "option.no": "いいえ",
  "validation.required": "この項目は必須です。",
  "validation.invalidType": "正しい形式で入力してください。",
  "validation.minLength": "{{min}}文字以上で入力してください。",
  "validation.maxLength": "{{max}}文字以内で入力してください。",
  "validation.pattern": "指定された形式で入力してください。",
  "validation.min": "{{min}}以上の値を入力してください。",
  "validation.max": "{{max}}以下の値を入力してください。",
  "validation.step": "{{step}}刻みで入力してください。",
  "validation.invalidOption": "選択肢から選んでください。",
  "validation.minSelections": "{{min}}つ以上選択してください。",
  "validation.maxSelections": "{{max}}つ以内で選択してください。",
  "validation.unknownField": "不明な項目が回答に含まれています。",
  "preview.language": "言語",
  "preview.success": "回答を保存しました。ありがとうございます。",
  "preview.error": "回答を保存できませんでした。もう一度お試しください。",
  "preview.analytics": "集計ダッシュボード",
  "preview.responses": "回答数",
  "preview.noResponses": "フォームを送信すると集計結果が表示されます。",
  "preview.answered": "回答済み",
  "preview.unanswered": "未回答",
  "preview.minimum": "最小",
  "preview.maximum": "最大",
  "preview.average": "平均",
  "preview.total": "合計",
  "preview.true": "チェック済み",
  "preview.false": "未チェック",
  "preview.builder": "フォームビルダー",
  "preview.mui": "MUI モード",
  "preview.comparison": "左右比較翻訳",
  "preview.respondent": "回答プレビュー",
  "preview.export": "CSVをダウンロード",
  "preview.schemaJson": "スキーマJSON",
  "preview.storage": "ストレージ",
  "preview.memory": "メモリ",
  "preview.localStorage": "LocalStorage",
  "preview.freeText": "自由記述回答",
  "preview.resetResponses": "回答データを全件クリア",
  "preview.resetConfirmation": "このフォームの回答をすべて削除しますか？",
  "preview.confirmReset": "削除を確定",
  "preview.cancel": "キャンセル",
  "preview.resetSuccess": "このフォームの回答をすべて削除しました。",
  "preview.resetError": "回答を削除できませんでした。",
  "preview.resetUnavailable": "選択中のストレージは回答リセットに対応していません。",
  "preview.crossTab": "クロス集計",
  "preview.rowQuestion": "行の質問",
  "preview.colQuestion": "列の質問",
  "preview.webhook": "Webhookシミュレーション",
  "preview.webhookUrl": "Webhook URL",
  "preview.simulateWebhook": "イベントを模擬送信",
  "preview.webhookSuccess": "Webhookの模擬送信に成功しました。",
  "preview.webhookError": "Webhookの模擬送信に失敗しました。",
  "builder.formBuilder": "フォームビルダー",
  "builder.moveUp": "「{{title}}」を上へ移動",
  "builder.moveDown": "「{{title}}」を下へ移動",
  "builder.delete": "「{{title}}」を削除",
  "builder.deleteAction": "削除",
  "builder.questionTitle": "質問文 / Question Title",
  "builder.questionTitlePlaceholder": "例: ご意見・ご要望をご記入ください",
  "builder.completionMessage": "完了メッセージ",
  "builder.newQuestionTitle": "新しい質問",
  "builder.type": "種類",
  "builder.required": "必須",
  "builder.minimum": "最小値",
  "builder.maximum": "最大値",
  "builder.options": "選択肢",
  "builder.optionLabel": "選択肢 / Option Label {{index}}",
  "builder.optionLabelPlaceholder": "例: 大変満足",
  "builder.newOptionLabel": "選択肢 {{index}}",
  "builder.remove": "削除",
  "builder.addOption": "選択肢を追加",
  "builder.displayCondition": "表示条件",
  "builder.alwaysVisible": "常に表示",
  "builder.conditionOperator": "条件演算子",
  "builder.conditionValue": "条件値",
  "builder.conditionTrue": "はい",
  "builder.conditionFalse": "いいえ",
  "builder.addQuestion": "質問を追加",
  "builder.pages": "ページ管理",
  "builder.enablePages": "マルチステップを有効化",
  "builder.addPage": "ページを追加",
  "builder.newPage": "新しいページ",
  "builder.pageTitle": "ページタイトル",
  "builder.pageDescription": "説明",
  "builder.pageQuestion": "新しいページへ移動する質問",
  "builder.questionPage": "所属ページ",
  "builder.pageCondition": "ページ表示条件",
  "builder.localization": "多言語管理",
  "builder.defaultLocale": "デフォルト言語",
  "builder.supportedLocales": "対応言語",
  "builder.addLocale": "言語を追加",
  "builder.editLocale": "編集する言語",
  "builder.autoTranslate": "すべて自動翻訳",
  "builder.translationUnavailable": "自動翻訳を有効にするには非同期翻訳アダプターを指定してください。",
  "builder.actions.addField": "質問を追加",
  "builder.fields.selectType": "質問種別を選択",
  "builder.fields.typeText": "テキスト",
  "builder.fields.typeTextarea": "テキストエリア",
  "builder.fields.typeNumber": "数値",
  "builder.fields.typeRating": "評価",
  "builder.fields.typeSelect": "単一選択",
  "builder.fields.typeMultiSelect": "複数選択",
  "builder.fields.typeCheckbox": "チェックボックス",
  "builder.fields.typeRadio": "ラジオボタン",
  "builder.fieldType.text": "テキスト",
  "builder.fieldType.textarea": "テキストエリア",
  "builder.fieldType.number": "数値",
  "builder.fieldType.rating": "評価",
  "builder.fieldType.select": "単一選択",
  "builder.fieldType.multi-select": "複数選択",
  "builder.fieldType.checkbox": "チェックボックス",
  "builder.fieldType.radio": "ラジオボタン",
  "builder.operator.equals": "等しい",
  "builder.operator.not_equals": "等しくない",
  "builder.operator.contains": "含む",
  "builder.operator.not_empty": "空ではない"
};

export const mockCatalogs: TranslationCatalogs = { en: sharedEnglish, ja: sharedJapanese };

export function createMockTranslationAdapter(
  catalogs: TranslationCatalogs = mockCatalogs,
  fallbackLocale = "en"
): TranslationAdapter {
  return {
    translate(key, locale, params = {}) {
      const template = catalogs[locale]?.[key] ?? catalogs[fallbackLocale]?.[key] ?? key;
      return template.replace(/\{\{(\w+)\}\}/g, (token, name: string) =>
        Object.hasOwn(params, name) ? String(params[name]) : token
      );
    }
  };
}

export const mockTranslator = createMockTranslationAdapter();

export function createMockAsyncTranslationAdapter(): AsyncTranslationAdapter {
  return {
    async translateText(text, targetLocale) {
      return `[${targetLocale}] ${text}`;
    },
    async translateBatch(texts, targetLocale) {
      return texts.map((text) => `[${targetLocale}] ${text}`);
    }
  };
}

export const mockAsyncTranslator = createMockAsyncTranslationAdapter();
